class AppConstants:
    # 金額の範囲
    MIN_BUGET = 0
    MAX_BUGET = 50000

    # 処理結果コード
    RESULT_CODE_SUCCESS = "00000"
    RESULT_CODE_SUCCESS_NO_RECIPE = "00001"
    RESULT_CODE_FAILURE_INVALID_INGREDIENT = "10001"
    RESULT_CODE_FAILURE_INVALID_BUGET = "10002"

    # 処理結果メッセージ
    RESULT_MESSAGE = {
        RESULT_CODE_SUCCESS: "レシピの取得に成功しました",
        RESULT_CODE_SUCCESS_NO_RECIPE: "レシピはありません",
        RESULT_CODE_FAILURE_INVALID_INGREDIENT: "無効な食材です",
        RESULT_CODE_FAILURE_INVALID_BUGET: "無効な予算です",
    }
